### ISSUE TITLE
Carlson_Passive_Myo.py contains hard coded file paths which cannot be run

### ISSUE THREAD

**Issue by alysclark** [sayakray111/Single-Vessel-Model#2]
For example:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ASUS/Desktop/Photos/My_Work/DAnometa2vals.mat'

**Comment by sayakray111** [comment]
done

**Comment by alysclark** [comment]
The issue that the script does not run remains. The correct way to call a file in the same folder looks like this "./perfusion(myo).csv" - please update
